version: '3.8'

services:
  grok-proxy:
    image: ghcr.io/songdaopi/grok-proxy:main
    container_name: grok-proxy
    ports:
      - "11451:11451"
    environment:
      - GROK_API_URL=https://grok.x.com/2/grok/add_response.json  # 如有需要，可修改
      - GROK_MODEL_OPTION_ID=grok-2 # 如有需要，可修改
    restart: unless-stopped