version: '3.8'

services:
  grok-proxy:
    image: ghcr.io/songdaopi/grok-proxy:main  # 或者您自己的镜像
    container_name: grok-proxy
    ports:
      - "11451:11451"
    environment:
      - GROK_API_URL=https://grok.x.com/2/grok/add_response.json
      - GROK_MODEL_OPTION_ID=grok-2
      - CT0=你的CT0值
      - CSRF_TOKEN=你的x-csrf-token值
      - QUERY_ID=你的QUERY_ID
      - CREATE_CONVERSATION_URL=https://x.com/i/api/graphql/你的QUERY_ID/CreateGrokConversation

    restart: unless-stopped